# Generated by Django 4.0.6 on 2022-07-06 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('created_date', models.DateTimeField()),
                ('last_push_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('star_count', models.IntegerField()),
            ],
        ),
    ]
