# Generated by Django 4.0.6 on 2022-07-06 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='star_count',
            new_name='number_of_stars',
        ),
    ]
