# Generated by Django 4.0.6 on 2022-07-06 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0002_rename_star_count_repository_number_of_stars'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'verbose_name_plural': 'repositories'},
        ),
        migrations.AlterField(
            model_name='repository',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='last_push_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
