# Generated by Django 4.0.6 on 2022-07-06 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0003_alter_repository_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='number_of_stars',
            field=models.IntegerField(null=True),
        ),
    ]
