# Generated by Django 4.0.6 on 2022-07-06 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0005_alter_repository_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='repo_id',
            field=models.IntegerField(unique=True),
        ),
    ]
